# -*- coding: utf-8 -*-
"""Agriculture Assistant ChatBot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMxFAgELiQxrLqjofOb51twS-gn6qJUY
"""

!pip install streamlit scikit-learn

import pandas as pd
import numpy as np
import nltk
import streamlit
import transformers

data = pd.read_csv('/content/drive/MyDrive/ChatBot/agriculture_data.csv')
data

def search_answer(query,data):
   for index, row in data.iterrows():
     if query.lower() in row['Question (Bangla)'].lower():
        return row['Answer (Bangla)']
   return "দুঃখিত, আপনার প্রশ্নের উত্তর খুঁজে পাওয়া যায়নি ।"

search_answer('ধান চাষের জন্য উপযুক্ত সার কোনটি?',data)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#prepare TF-IDF Vectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(data['Question (Bangla)'])

def get_best_match(query):
  query_vector = vectorizer.transform([query])
  similarities = cosine_similarity(query_vector, tfidf_matrix)

  best_match_index = similarities.argmax()

  return data.iloc[best_match_index]['Answer (Bangla)']

get_best_match('কৃষকদের জন্য সর্বশেষ সরকারি সুবিধা কি?')

import streamlit as st

st.title("🌾 বাংলা কৃষি পরামর্শ চ্যাটবট")
st.subheader("আপনার কৃষি সংক্রান্ত প্রশ্ন লিখুন")

data = data

user_query = st.text_input("আপনার প্রশ্ন লিখুন ( বাংলায়)")

if st.button("পরামর্শ নিন"):
   if user_query:
     answer = get_best_match(user_query)
     st.success(f"📢 পরামর্শ : {answer}")
   else:
     st.warning("⚠ অনুগ্রহ করে একটি প্রশ্ন লিখুন।")


import random

if st.button("👨‍🌾 দৈনিক কৃষি পরামর্শ"):
  random_tip = random.choice(data['Answer(Bangla)'])
  st.info(f"✅ {random_tip}")